In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
# Q1
a = [1, 2, 3]
b = [4, 5]
a.append(b)
print(a)
a.extend(b)
print(b)
print(a)

[1, 2, 3, [4, 5]]
[4, 5]
[1, 2, 3, [4, 5], 4, 5]


In [4]:
# Q2
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
df = pd.read_csv('fuel_ferc1.csv')

In [6]:
# Q4
sd1=df['fuel_mmbtu_per_unit'].std()
perf75=df['fuel_mmbtu_per_unit'].quantile(.75)
print(np.round(sd1, decimals=2),np.round(perf75,decimals=2))

10.6 17.01


In [7]:
# Q5 
skew1=df.skew()['fuel_qty_burned']
kurs1=df.kurtosis()['fuel_qty_burned']
print(np.round(skew1, decimals=2), np.round(kurs1, decimals=2))

15.85 651.37


In [8]:
# average cost per unit delivered for each year will be mean of all the costs
df1 = df.loc[df['report_year'] == 1997]
dfm1=df1['fuel_cost_per_unit_delivered'].mean()
# 2004
df2 = df.loc[df['report_year'] == 2004]
dfm2=df2['fuel_cost_per_unit_delivered'].mean()
# 1996
df3 = df[df['report_year'] == 1996]
dfm3=df3['fuel_cost_per_unit_delivered'].mean()
# 2009
df4 = df.loc[df['report_year'] == 2009]
dfm4=df4['fuel_cost_per_unit_delivered'].mean()
# 2018
df5 = df.loc[df['report_year'] == 2018]
dfm5=df5['fuel_cost_per_unit_delivered'].mean()

#save to a series and get max
ds = pd.Series([dfm1,dfm2,dfm3,dfm4,dfm5], index=[1997, 2004, 1996, 2009, 2018])
print(ds)

# minimum value using the max method
print(ds.max())

1997    11140.197239
2004      139.524275
1996     9196.705948
2009      652.694163
2018      499.269966
dtype: float64
11140.19723948813
